server:
  port: 9296

spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Subhanshu-2411/config_server-Spring_Boot.git
          clone-on-start: true